run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - errorlint
    - copyloopvar
    - gosec
    - unconvert
    - unparam
    - gocyclo
    - govet
    - misspell
    - nilerr
    - gofmt

linters-settings:
  gocyclo:
    min-complexity: 25
  govet:
    enable:
      - shadow
  misspell:
    locale: US

issues:
  exclude-dirs:
    - codegen
  exclude-rules:
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows'
    - path: 'zz_(.+)\.go'
      linters:
        - gosec
        - gofmt
